[package]
name = "wormhole"
version = "1.0.0"
edition = "2024"
author = "Joseph Joseph"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
colored = "3.0.0"
ctrlc = "3.4.7"
figlet-rs = "0.1.5"
local-ip-address = "0.6.5"
qrcode = "0.14.1"
rand = "0.9.2"
tiny_http = "=0.12.0"
