[package]
name = "wormhole"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
hyper = "1.6.0"
local-ip-address = "0.6.5"
qrcode = "0.14.1"
tokio = { version = "1.46.1", features = ["full"] }
